name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write

jobs:
  review:
    # コメントでも「PRに紐づくコメント」だけ通す
    if: >
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      # PRのheadを確実にチェックアウト
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Claude Review
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          trigger_phrase: "@claude"
          label_trigger: "claude"
          claude_args: |
            --model claude-sonnet-4-20250514
            --max-turns 6
        env:
          # 保険として環境変数でも渡す
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        # 最後の保険：失敗でもジョブ全体を赤にしない（動作確認中のみ）
        continue-on-error: true
